### ISSUE TITLE
Missing return statement?

### ISSUE THREAD

**Issue by Caster** [nathanbabcock/google-drive-cms#1]
Thanks for the great [article](https://css-tricks.com/using-google-drive-as-a-cms/) and for sharing this code. Now I haven't run this code, let alone tested it really, but I noticed that the `getSheet` function doesn't return early if an error occurs. Shouldn't there be a return statement on [line 128](https://github.com/nathanbabcock/google-drive-cms/blob/master/driveAPI.js#L128)? There [is one](https://github.com/nathanbabcock/google-drive-cms/blob/master/driveAPI.js#L162) in the similar `getDoc` function.

I'm happy to create a pull request if needed.

**Comment by nathanbabcock** [comment]
Hey Caster, thanks for the kind words. You're absolutely correct, it should have a `return reject()` just like `getDoc`.

If you're so inclined to create a PR I will happily merge it and release a patch on npm as well.

**Comment by Caster** [comment]
Thanks, I just created a PR. Just for completeness, you may also want to update the [article](https://css-tricks.com/using-google-drive-as-a-cms/#fetching-a-sheet) (that's where I read it, I didn't start snooping around in the code :grin:).

**Comment by nathanbabcock** [comment]
Thanks for the PR.

Merged, bumped version # and released the fix on NPM.

Also updated the original article: [Using Google Drive as a CMS](https://css-tricks.com/using-google-drive-as-a-cms/#fetching-a-sheet).
